### ISSUE TITLE
patch-sizes example seems not to be working by now

### ISSUE THREAD

**Issue by Loksly** [thekevinscott/UpscalerJS#118]
**Describe the bug**

https://github.com/thekevinscott/UpscalerJS/tree/master/examples/patch-sizes

**To Reproduce**
This is the url that [patch-sizes/README.md](https://github.com/thekevinscott/UpscalerJS/blob/master/examples/patch-sizes/README.md) links to:

https://codesandbox.io/s/github/thekevinscott/upscalerjs/tree/master/examples/patch-sizes

**Expected behavior**
Runs flawlessly

**Screenshots**
![image](https://user-images.githubusercontent.com/1235649/128193003-03bdfe63-3d05-4bca-9415-67901b1a45c1.png)

**Comment by thekevinscott** [comment]
Still working on fixing this.

The primary issue was that the location of the two exported functions changed. I've updated both to be exported from the root, but now see a new problem:

<img width="717" alt="Screen Shot 2021-08-10 at 9 21 41 AM" src="https://user-images.githubusercontent.com/151596/128874391-27a4151f-4d97-4395-8a9e-10e97bf56bc1.png">

**Comment by thekevinscott** [comment]
This should not have been closed, I’ve removed stalebot.

**Comment by thekevinscott** [comment]
This should now be fixed.
