### ISSUE TITLE
realDivide missing in tfjs-node

### ISSUE THREAD

**Issue by danwexler** [thekevinscott/UpscalerJS#12]
The tf.div in models/idealo-gans.js fails when running using tfjs-node on Ubuntu. I get the following error:

`'realDivide' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen`

I do NOT see this error running using the CPU backend on OSX. Everything works fine. On Ubuntu it fails. I've tested this using the 1.15.5 tensorflow gpu installation with both the latest tfjs-node-gpu@2.8.5 and with the earlier version that matches the upscaler package.json, tfjs-node-gpu@2.1.0. I have not yet dug into the TFJS or TF side of things to find the bug.

A simple workaround is:

```
--- a/node_modules/upscaler/dist/models/idealo-gans.js
+++ b/node_modules/upscaler/dist/models/idealo-gans.js
@@ -38,7 +38,7 @@ PixelShuffle.className = 'PixelShuffle';
 const config = {
     urlPath: 'idealo/gans',
     scale: 4,
-    preprocess: (image) => tf.div(image, 255),
+    preprocess: (image) => tf.mul(image, 1 / 255),
     postprocess: (output) => tf.mul(output.clipByValue(0, 1), 255),
     customLayers: [MultiplyBeta, PixelShuffle],
 };
```

**Comment by thekevinscott** [comment]
This is a great find (and sorry for the delay in response, @danwexler ). Would you be open to making this a PR?

**Comment by danwexler** [comment]
Yep. Will do. FYI, I have found a number of memory leaks in the code as well, which are particularly visible when running in Node on a GPU. I'll try to make a separate PR for those fixes as well.

**Comment by thekevinscott** [comment]
Awesome, looking forward to it!

If you haven't started yet, make sure to pull master. I pushed a refactor that moves code into `packages/upscalerjs`, so that I was able to import the models from https://github.com/thekevinscott/UpscalerJS-models into this repo.

**Comment by thekevinscott** [comment]
Whoops, I didn't realize this was already fixed by https://github.com/thekevinscott/UpscalerJS/pull/60/files
