### ISSUE TITLE
Demo page is broken

### ISSUE THREAD

**Issue by thekevinscott** [thekevinscott/UpscalerJS#1243]
The demo page is currently broken (thanks to @wes-kay on #1217 for the report)

**Comment by wes-kay** [comment]
> It still is... 

_This isn't what I didn't pay for._


I don't particularly need the demo scene as I've seen the outputs as that's all I needed. 

Thanks.

**Comment by av01d** [comment]
> > It still is...
> 
> _This isn't what I didn't pay for._
> 
> I don't particularly need the demo scene as I've seen the outputs as that's all I needed.
> 
I'm struggling to replicate the demo upscaled images as seen on the homepage of upscalerjs.com.
I'm pretty sure I've got things running correctly, but my upscaled images don't look half as good as they do in the demo carousel on uplscalerjs.com. 
A demo page would be very handy to confirm that this lib does what it promises to do *in my browser*.

**Comment by thekevinscott** [comment]
The demo page should be fixed now. Please let me know if you're still seeing issues.

The demo is using the [`esrgan-medium`](https://upscalerjs.com/models/available/upscaling/esrgan-medium), so if you're comparing models make sure you're comparing to that (I also realize the demo page doesn't say which model it's using; [made an issue for that here](https://github.com/thekevinscott/UpscalerJS/issues/1261)).

The images from the carousel on the homepage are using `esrgan-thick`, which is the highest quality but also slowest model. Normally [you can run a demo of it in your browser here](https://upscalerjs.com/models/available/upscaling/esrgan-thick?metrics=PSNR&datasets=Div2K&devices=iPhone+14+Pro+Max#demo), but it looks like Codesandbox isn't picking up the latest dependencies that I published, so alternatively you can download the repo and run the demo locally with:

```
cd models/esrgan-thick/demo
npm install
npm run dev
```

And you should see it running at http://localhost:5173.

**Comment by thekevinscott** [comment]
I'll close as fixed, but if you're still seeing issues with the demo I will re-open this and investigate further.

**Comment by av01d** [comment]
The demo page works now, thanks for that. There's a bug on Firefox though: if you select an image from the Pixabay list on the right, an "The operation is insecure" error is thrown. Probably a crossorigin issue. It does work on Chrome and Safari.

**Comment by thekevinscott** [comment]
Ah yes, I see that too - thanks for the report. Will reopen this.
