### ISSUE TITLE
Cannot reproduce your results

### ISSUE THREAD

**Issue by av01d** [thekevinscott/UpscalerJS#1256]
**Describe the bug**
I am having trouble reproducing the rather awesome upscaling results I see on www.upscalerjs.com.
The carousel on top of that page shows that the upscaled images are indeed much more detailed/sharp than the originals.
When I set up a similar test on jsfiddle, the results are much less stellar.
https://jsfiddle.net/av01d/gopuyeqs/

I am clearly missing something... but what?

**To Reproduce**
Visit https://jsfiddle.net/av01d/gopuyeqs/

**Expected behavior**
Clear, sharp upscaled images.

**Screenshots**
![Screenshot 2023-11-16 at 15 33 22](https://github.com/thekevinscott/UpscalerJS/assets/6247646/69f1c38b-10db-406b-b485-df63f3277878)

**Comment by thekevinscott** [comment]
Thanks for the jsfiddle link - it's always helpful when someone takes the time to create a reproducible example!

A few things:

- [Like I mentioned here](https://github.com/thekevinscott/UpscalerJS/issues/1243#issuecomment-1817583233), you'll want to use `esrgan-thick` to get the same results as the homepage examples. `esrgan-slim` and `esrgan-medium` are lower quality models that run much faster.
- You can't instantiate the model by simply passing a URL to the model JSON, as there's model configuration that needs to be set up as well. You need to pass a reference to the model configuration file. [This example walks through the specifics of installing and using a model](https://upscalerjs.com/documentation/guides/browser/models). If you're referencing the files outside of npm (like it appears you're doing here) you'll want to use the UMD builds, [information on that can be found here](https://upscalerjs.com/models/available/upscaling/esrgan-thick?metrics=PSNR&datasets=Div2K&devices=iPhone+14+Pro+Max#using-a-script-tag).
- This is something I've never encountered: it appears that if you set an explicit width and height on the input image, those dimensions carry through even if the original image src is smaller. Here, you're setting an image width and height of 512px which, for the browser, can take a long time to process. Instead I'd recommend you pass the original image src, which will process faster.
- Your original image is 128px and you've set the width and height to 512, so I assume you're looking for a 4x upscale. You need to specify the model corresponding to the desired scale, which in this case is 4x. The larger the upscale, the less accurate the upscaled image will be.

Here is a JSFiddle that implements the above bullets: https://jsfiddle.net/thekevinscott/f5e3h189/38/

<img width="1786" alt="Screenshot 2023-11-18 at 1 35 28 PM" src="https://github.com/thekevinscott/UpscalerJS/assets/151596/0d4e08ce-6827-4f22-b901-33446bdb1f58">

**Comment by av01d** [comment]
Thank you very much for your concise answers. Thanks to your fiddle I understand what I needed to change, got it working just fine now.

**Comment by av01d** [comment]
Thank you very much for your concise answers. Thanks to your fiddle I understand what I needed to change, got it working just fine now.
