### ISSUE TITLE
Support for transparent images

### ISSUE THREAD

**Issue by adityapatadia** [thekevinscott/UpscalerJS#1271]
Currently, only 3 channel images are supported. Is there any plan to add support for transparent images like PNG?

**Comment by thekevinscott** [comment]
There is not. See this earlier question for a more [in-depth discussion](https://github.com/thekevinscott/UpscalerJS/issues/8).

To enable transparent support you'd need to train an implementation of ESRGAN on a dataset of transparent images. The linked question thread should have some pointers on how you would do that. The biggest challenge (imo) is finding a dataset of transparent images comparable in breadth to the div2k dataset.

If you do end up training a model, I'd love to invite you to add it to this repo, as I'm sure other would love to leverage it as well.
