### ISSUE TITLE
@tensorflow/tfjs-node

### ISSUE THREAD

**Issue by AugustoJDev** [thekevinscott/UpscalerJS#1286]
**Describe the bug**
I am unable to download the dependencies. It is giving a lack of permissions error

**To Reproduce**
npm i @tensorflow/tfjs-node upsaler/node

**Expected behavior**
Download the NPM

**Screenshots**
![](https://cdn.discordapp.com/attachments/1199743216132558941/1199872122340786258/image.png?ex=65c41efe&is=65b1a9fe&hm=05d79ad1ebf1d5da2bcd61a4991d402f0a3e575fc537f3113fc04928f513deaf&)

**Comment by thekevinscott** [comment]
It should be:

```
npm i upscaler
```

In your Node.js code you would then import it with the slash:

```
const upscaler = require('upscaler/node');
```

Let me know if that resolves it

**Comment by thekevinscott** [comment]
Closing this as stale - please reopen if you're having issues.
