### ISSUE TITLE
Open Collective, Buy Me A Coffee or GitHub Sponsors?

### ISSUE THREAD

**Issue by addyosmani** [thekevinscott/UpscalerJS#13]
I would love to give a small donation for the great work done on this repo and its supporting work. Is there a preferred place to do this, @thekevinscott? :)

**Comment by thekevinscott** [comment]
Oh gosh, I appreciate that very much! I've yet to set up Github Sponsors, but I [do have an e-book for sale](https://gumroad.com/l/dljsbook) at a pay-what-you-want price point. I'd also love any feedback / things you're interested in learning more about as I prepare a second edition!

**Comment by addyosmani** [comment]
Purchased with a tip! :) 

Thank you so much for the great work on both this project and the approachable book. In my work, I've had the opportunity to meet with the TensorFlow.js team a few times over the years - I've always felt like we were missing more compelling use-cases for ideas with models that could be executed relatively quickly client-side (and could still do well enough on mobile Snapdragon CPUs). Upscaler checked that box for me in terms of "YES. This is exactly the type of use-case I've been looking for".

I'm not sure if this is interesting, but the [tweet](https://twitter.com/addyosmani/status/1353616560057815041) about my use of this project had 264K impressions. I feel like there are a lot of developers out there that are interested in use-cases for TF.js like upscaling but just aren't aware what is currently possible with deep-learning on the client. Perhaps an opportunity here for an egghead.io course on TF.js or further educational material?

In terms of some feedback:

* Quite specific to TF.js, I think there is a lot of misunderstanding around slowness (see issue 14 as an example). This is due to slower CPUs and GPUs (and makes sense if you understand mobile hardware or are interested in Web Performance) but I think it could be interesting to bring folks up to speed on the trade-offs between client-side vs server-side deep learning and what the expectations they should have are.
* As someone who was familiar with DIV2K and GAN, I was surprised to learn how prevalent [waifu2x](https://github.com/nagadomi/waifu2x) has been in the image super resolution space. I've been incorporating a mode for this in my app and think it could be interesting to give folks a primer on the different models and trade-offs for specific deep learning use-cases like this.

As I read through the book, will be sure to share any additional feedback I have. Thank you!
