### ISSUE TITLE
Input format error in tfjs, not sure how to fix at the callsite

### ISSUE THREAD

**Issue by just-toby** [thekevinscott/UpscalerJS#15]
`IMG <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 03 e8 00 00 03 e8 08 06 00 00 00 4d a3 d4 e4 00 00 00 01 73 52 47 42 00 ae ce 1c e9 00 00 20 00 ... 188663 more bytes>
(node:22926) UnhandledPromiseRejectionWarning: Error: Error when checking : expected LR_input to have shape [null,null,null,3] but got array with shape [1,1000,1000,4].
    at new ValueError (/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:189:28)
    at checkInputData (/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:8794:31)
    at LayersModel.predict (/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:9422:9)
    at /node_modules/upscaler/dist/upscale.js:256:42
    at /node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3347:22
`

**Comment by just-toby** [comment]
the file i'm calling `upscaler.upscale` on is just a PNG formatted file

**Comment by thekevinscott** [comment]
@just-toby can you provide a runnable code example (e.g., on codesandbox.io), or a Github repo demonstrating?
