### ISSUE TITLE
Complete Black image on Upscaling via GAN4k

### ISSUE THREAD

**Issue by Ramstein** [thekevinscott/UpscalerJS#151]
**Describe the bug**

**To Reproduce**
Please provide a link to runnable code on http://codesandbox.io/ (preferred), or a link to a repository demonstrating the issue.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thekevinscott** [comment]
Thanks for the report @Ramstein. I need some more information to debug - browser / OS, and ideally a runnable codesandbox link (or a link to one of the examples that's broken).

**Comment by thekevinscott** [comment]
Closing - please provide more information and we can reopen.
