### ISSUE TITLE
Outdated tfjs version 

### ISSUE THREAD

**Issue by LuckyMallari** [thekevinscott/UpscalerJS#152]
**Describe the bug**

Outdated tfjs version. Integrating your lib with a project that uses a more modern tfjs breaks npm install.
```
npm ERR! While resolving: XXXXX@XXXX
npm ERR! Found: @tensorflow/tfjs@3.12.0
npm ERR! node_modules/@tensorflow/tfjs
npm ERR!   dev @tensorflow/tfjs@"^3.12.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @tensorflow/tfjs@"2.8.6" from upscaler@0.8.27
npm ERR! node_modules/upscaler
npm ERR!   upscaler@"*" from the root project
```

Also, you are explicitly stating a version. Target either a major or a minor version instead:
```
"@tensorflow/tfjs": "2.8.6",
```

**To Reproduce**
Create another project that depends on tfjs 3+

**Expected behavior**
`npm install` should resolve

**Comment by thekevinscott** [comment]
This is now published as `0.9.0` on `npm`.
