### ISSUE TITLE
Load models from file system

### ISSUE THREAD

**Issue by LuckyMallari** [thekevinscott/UpscalerJS#153]
**Describe the bug**
https://github.com/thekevinscott/UpscalerJS/blob/c8f5aeff9e6e70cb41d7b773be5b34416bf2ecca/packages/upscalerjs/src/loadModel.ts#L134

Because description is retrieved using fetch, this will only work for models from the are exposed as HTTP/s resource.

Instead of using just `fetch`, check if parameter contains http/https protocol. if not, assume it is a trying to retrieve using file system.

*This is for nodejs based implementations

**To Reproduce**
Load a model using filesystem

**Expected behavior**
Should load model from file system

**Comment by thekevinscott** [comment]
@LuckyMallari thanks for reporting.

Are you asking that a local model expose it's configuration through the file system on Node? Or simply that fetch work correctly in the Node environment?

The latter is fixed and available in the branch #185. It's also available on `npm` as `0.10.0-canary.2`.

**Comment by LuckyMallari** [comment]
Local file system is fine, just feed it with path and should make it more useable.

**Comment by thekevinscott** [comment]
This particular method is for fetching and exposing descriptions of available models. The provided models are stored separately from the UpscalerJS package and are served via a CDN (currently, `unpkg`). That package is on `npm` at [`@upscalerjs/models`](https://www.npmjs.com/package/@upscalerjs/models).

There's no mechanism in UpscalerJS for fetching a local model's description and exposing it. You can of course provide a local custom model, but there's no way to read it's local description, as these particular fetched descriptions are hard coded [to match the models we have on record](https://github.com/thekevinscott/UpscalerJS/blob/main/packages/upscalerjs/src/models.ts#L25).

(As an aside, I'd like to revisit how this package handles and exposes models ([you are welcome to contribute to the discussion here!](https://github.com/thekevinscott/UpscalerJS/discussions/30)) and I think this is a prime candidate for a function to cut. IMO, local model discovery is not a very good use for code (versus, say, browsing NPM for available models).)

I'd love to hear a little bit more about your use case. Are you looking to have the model descriptions available in the core of the package? Or are you looking for a way to programmatically expose custom model descriptions via the Upscaler?

**Comment by LuckyMallari** [comment]
Thanks for the response. A good use case is a completely offline usage. A low resolution camera capture that upscales the image as a preprocessing step. With it being offline, fetch would not work unless I host and run a light server on the same macgine just to fetch the description. The current implementation makes internet connection a requirement.

**Comment by thekevinscott** [comment]
I'm going to close this issue. Please let me know if you are still seeing it on the latest beta release.
