### ISSUE TITLE
Wrong image displayed as result while calculating the upscaled version

### ISSUE THREAD

**Issue by LokiMidgard** [thekevinscott/UpscalerJS#173]
**Describe the bug**
When upscaling an Image the percentage is jumping forth and back (for some time). And then it shows the result of the last image upscaled before being finished.

You can look at the screenshot below, it will displayed an image I upscaled before (from the samples of this site) while still showing the percentage that it is not finishied. I assume it was shortly at or over 100% and then displayed the result which was still the old image.

**To Reproduce**
Upscale an image, then click on `upscale another` and upload (propably a big) image.

I used the following:

![6d56828e-5152-4bbe-8ccf-50f2e5faef60](https://user-images.githubusercontent.com/389101/150948203-356c7f00-8f47-45b6-877c-1e6c8be2c8fb.png)

Which by the way will not work at all.

**Expected behavior**
Not showing an old image

**Screenshots**
![image](https://user-images.githubusercontent.com/389101/150947776-35e7dbb5-1405-48a7-a0b4-a5de8698a85b.png)

**Additional context**
I used brave browser and the image I used was to big to handle it correctly, I assume the same issue can occure with smaller images, but may be so shortly visible that it is not noticed. I used GANs

**Comment by thekevinscott** [comment]
Thanks for reporting in @LokiMidgard - I'm focused on wrapping up the Node support branch (#185) but once that's complete I'll take a look at this and the other bug you reported.

**Comment by danwexler** [comment]
@LokiMidgard if you haven't already, you should use tiling to compute the larger images. You need to se the patchSize and padding options to something that fits on the GPU, like patchSize=256 and padding=4.

**Comment by thekevinscott** [comment]
I've gotten a few confused queries around what the relationship is between https://upscaler.ai and the regular UpscalerJS is. It's meant to be a demonstration of UpscalerJS on the web without having to set it up yourself. As such, I think it's best to consolidate the demo under the UpscalerJS docs page to reduce confusion.

I've refactored the code and launched that here (currently an unlisted URL):

https://upscalerjs.com/demo

This should address the bug you've listed here @LokiMidgard. Please let me know if you're still seeing it.

**Comment by thekevinscott** [comment]
(Also, any feedback on that new page is welcome!)

**Comment by thekevinscott** [comment]
I'm going to close this and #174, as the old upscaler.ai is defunct (it redirects to the new demo page). Please feel free to open a new bug report for any issues found on the new demo page.
