### ISSUE TITLE
Import Error when Attempting to use Node-gpu

### ISSUE THREAD

**Issue by nminchow** [thekevinscott/UpscalerJS#285]
**Describe the bug**
When I attempt to `import Upscaler from 'upscaler/node-gpu';` I encounter an `ERR_MODULE_NOT_FOUND`:

```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\projects\image_upscaler\node_modules\upscaler\dist\node-gpu\cjs\cjs.js' imported from D:\projects\image_upscaler\index.mjs
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:405:11)
    at moduleResolve (node:internal/modules/esm/resolve:966:10)
    at defaultResolve (node:internal/modules/esm/resolve:1176:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.0.0
```

I'm attempting to follow the instructions here: https://github.com/thekevinscott/UpscalerJS/issues/11#issuecomment-1053724395, and [in the quickstart](https://github.com/thekevinscott/UpscalerJS/tree/main/docs#quick-start).

**To Reproduce**
https://github.com/nminchow/cmd-line-upscaler/commit/a1c19c4b42ce6099a416829fd7c58152814585e8 on [this branch](https://github.com/nminchow/cmd-line-upscaler/tree/use-gpu-upscaler) introduces the error. I'm just not seeing that folder in node_modules (see screenshot). The [readme ](https://github.com/nminchow/cmd-line-upscaler/tree/switch-to-2x-model#readme)should allow you to test end-to-end locally.

**Screenshots**
![image](https://user-images.githubusercontent.com/7690508/164372843-f8429f84-5a0f-428a-b888-efa5465f84fd.png)

**Comment by thekevinscott** [comment]
Thank you for the bug report and the instructions on how to reproduce, @nminchow.

In `0.12.3` (just published) the `node-gpu` folder should be present in `dist`. Let me know if you're still seeing issues.
