### ISSUE TITLE
upscaler.ai website gone (replaced with a basic html page)

### ISSUE THREAD

**Issue by cedriclikescode** [thekevinscott/UpscalerJS#428]
**Describe the bug**
visiting http://upscaler.ai shows a blank page with "This domain was recently registered at Namecheap.com.".

**To Reproduce**
simply go to http://upscaler.ai

**Expected behavior**
the website should not be a blank page

**Screenshots*
![upscale ai gone](https://user-images.githubusercontent.com/104719938/181996312-deb9acc5-139c-49eb-a867-fb58ae401e11.png)

**Additional context**
visiting the https version (https://upscaler.ai) will not load at all (upscaler.ai took too long to respond)

**Comment by cedriclikescode** [comment]
Never mind, website works now.

**Comment by thekevinscott** [comment]
Thank you for reporting this @cedriclikescode - the DNS had expired, so I had to go ahead and renew. My bad!
