### ISSUE TITLE
Upscaling finishes but no change in image. GPU process exited unexpectedly

### ISSUE THREAD

**Issue by NayamAmarshe** [thekevinscott/UpscalerJS#430]
**Describe the bug**
```
$ electron ./dist/main.bundle.js
[518473:0804/111543.477611:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=512
[518534:0804/111543.460699:ERROR:command_buffer_proxy_impl.cc(329)] GPU state invalid after WaitForGetOffsetInRange.
Done in 206.53s.
```

**To Reproduce**
I'm using React.js in Electron.js. The code is exactly the same as in the code examples, the only difference is it's running in electron.js

**Expected behavior**
Upscaled Image should be different

**Screenshots**
![image](https://user-images.githubusercontent.com/25067102/182772587-c73f8abf-943a-4841-b45f-64e3864147a7.png)

**Additional context**
I also get this in console
![image](https://user-images.githubusercontent.com/25067102/182772724-de2d8f2f-a263-4450-8c08-b59d421b3ac7.png)

**Comment by NayamAmarshe** [comment]
Any suggestions?

**Comment by thekevinscott** [comment]
Sorry, I haven't had a chance to look at this yet. I'm not very familiar with Electron, could you provide a repo that reproduces this?

**Comment by danwexler** [comment]
This can happen if you use a large source image and do not enable tiling by setting the patchSize and padding options. Can you set patchSize=256 and padding=4 and retest?

**Comment by thekevinscott** [comment]
Added an example working with Electron at https://upscalerjs.com/documentation/guides/browser/implementations/electron
