### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by stvegerrad** [thekevinscott/UpscalerJS#455]
**Describe the bug**
I tried to run some examples but it shows this error: "**@parcel/core: Failed to resolve '@upscalerjs/esrgan-slim' from
'./node_modules/upscaler/dist/browser/esm/dependencies.generated.js'**"

**To Reproduce**
1. git clone the project
2. cd examples/progress
3. yarn install, yarn start

**Expected behavior**
Should be run without any issues

**Screenshots**
![image](https://user-images.githubusercontent.com/108422664/187874126-4fb2f889-b5d9-4dd2-9004-0222a0f9eb62.png)

**Comment by thekevinscott** [comment]
Thanks for reporting this, @stvegerrad.

Out of curiosity, can you run the example in `examples/basic`?

(Most of the examples I still need to update for `1.0.0`, but `basic` should be one of the few that's been updated already.)

**Comment by stvegerrad** [comment]
Got it.
I already test `examples/basic` project and it works well.
Excuse me, could you tell me how long does it take to update full examples to the current version?

**Comment by thekevinscott** [comment]
Hard to say - some should be quick to change over, but others will require some refactoring. 

I can prioritize the ones you're interested in, or else I'll just go in alphabetical order.

**Comment by thekevinscott** [comment]
The following examples are updated and should be working:

- basic
- cancel
- progress
- react-demo
- tensor
- upload
- warmup
- webcam

The others still have some sort of related bug which I'm working on fixing.

**Comment by stvegerrad** [comment]
Thanks for your effort.

**Comment by thekevinscott** [comment]
All the examples should now be updated. Please take a look!

For any issues with particular examples, please open a new issue for that bug.
