### ISSUE TITLE
Upscaler.ai demo - broken link + question about settings used

### ISSUE THREAD

**Issue by predmunds** [thekevinscott/UpscalerJS#473]
Firstly, thanks so much for the live demo of the upscaler.js at upscaler.AI
I tried it on some incredibly complex images and found that the 4xGANS  upscaling was very effective at filling in detail and retaining the colour and contrast of the original image.

just a couple of things related to the upscaler.AI demo

The link at the bottom of the demo page is broken. This is where it is directed to, with a 404 message. 

https://thekevinscott.github.io/UpscalerJS/#/

OPTION SETTINGS for live DEMO
Can you please let us know what options are being used for the live demo if I am using the option to upscale using GANSx4  and using a photograph, rather than an animated or cartoon image.

So, which of the esrgan models are used on the demo in this case. Is it the slim or legacy? 
What settings are used for patch size and padding etc. 
Knowing all of this this will help me understand the app and aid my future use of app. 

maybe the settings info could be added at the bottom of the demo web page. 

Thanks again.  
predmunds

**Additional context**

**Comment by thekevinscott** [comment]
Thanks for the kind words @predmunds!

> The link at the bottom of the demo page is broken. This is where it is directed to, with a 404 message.

Thanks for letting me know.

> OPTION SETTINGS for live DEMO
> Can you please let us know what options are being used for the live demo if I am using the option to upscale using GANSx4 and using a photograph, rather than an animated or cartoon image.
> ...
> What settings are used for patch size and padding etc.

Firstly, the code instantiating the upscaler on https://upscaler.ai [can be found here](https://github.com/thekevinscott/Upscaler.ai/blob/master/src/containers/Upscaled/upscaler.worker.ts#L27). 

Something to point out is that [it is using an old version of the upscaler, at `0.7.x`](https://github.com/thekevinscott/Upscaler.ai/blob/master/package.json#L66). So there's a few differences from the 1.x beta.

The specific configuration it's using includes:

* It uses the `idealo/gans` model by default
* It uses a patch size of 32px and a padding of 4px
* It gets warmed up with the same sizes
* It runs in a web worker

> So, which of the esrgan models are used on the demo in this case. Is it the slim or legacy?

[See my answer here for more context](https://github.com/thekevinscott/UpscalerJS/issues/447#issuecomment-1221292858). In short, `esrgan-legacy` contains all the models available on https://upscaler.ai, and `esrgan-slim` is the `idealo/gans` model.

> maybe the settings info could be added at the bottom of the demo web page.

[I've heard from a number of folks that are confused by the existence of a stand-alone demo for UpscalerJS](https://github.com/thekevinscott/UpscalerJS/issues/174#issuecomment-1235602647); as a result, I'm working on a new demo page for it that will live on the docs site. You can try that here:

http://upscalerjs.com/demo

It's a bit different in that it doesn't have model selection (yet) but it should also be more performant and running the latest version of the Upscaler. My intention is to redirect upscaler.ai to this new demo site once I work out all the bugs.

**Comment by thekevinscott** [comment]
I'm going to go ahead and close this but feel free to ask more questions pertaining to the Upscaler instantiation here.
