### ISSUE TITLE
Plz, could U give a clue to resolve npm warn and chrome error?

### ISSUE THREAD

**Issue by xztema0207** [thekevinscott/UpscalerJS#5]
I try to install "npm install upscaler" as you guided in document. 
but, there are some warn message as follow. 
and then in chrome, there are err msg like "Uncaught SyntaxError: Cannot use import statement outside a module"

Plz, could U give a clue to resolve the npm err and chrome err?

===============================
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Invalid version: "/mnt/Castellan/code/upscalerjs/scripts/bump_version.js"
npm WARN upscaler@0.7.4 requires a peer of @tensorflow/tfjs@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN tensor-as-base64@0.1.1 requires a peer of @tensorflow/tfjs@^2.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN UpscalerJS No description
npm WARN UpscalerJS No repository field.
npm WARN UpscalerJS No README data
npm WARN UpscalerJS No license field.
================
Thanks.

**Comment by mostlyfabulous** [comment]
>upscaler@0.7.4 requires a peer of @tensorflow/tfjs@^2.1.0 but none is installed. You must install peer dependencies yourself.
>tensor-as-base64@0.1.1 requires a peer of @tensorflow/tfjs@^2.0.1 but none is installed. You must install peer dependencies yourself.

Just `npm install` those missing peer dependencies.

**Comment by thekevinscott** [comment]
Like @mostlyfabulous said - you have to install the dependencies yourself.
