### ISSUE TITLE
The live demo link

### ISSUE THREAD

**Issue by BooLightning** [thekevinscott/UpscalerJS#505]
**Describe the bug**
The demo will not load

**To Reproduce**
Go to https://upscaler.ai/

**Expected behavior**
A loaded website

Relevant screenshot
![7765EFAE-BFF5-4DDF-8704-14C84A901963](https://user-images.githubusercontent.com/99196881/192896250-df1371ba-0b28-492e-96ab-3dfc7a7d2ae9.jpeg)

**Comment by thekevinscott** [comment]
Thanks for reporting this, @BooLightning.

I think the DNS records may still be propagating. I've just rechecked `downfor.io` and it's looking like it's up now:

<img width="1098" alt="Screen Shot 2022-09-29 at 5 27 58 AM" src="https://user-images.githubusercontent.com/151596/192995146-54630265-159c-4779-8a45-07a9439bb7dd.png">

Could you clear your cache (or try a different browser) and report back your findings? If you're still seeing this, can you tell me which browser? (For me, Firefox is working fine, but Chrome and Safari both appear to have cached the DNS)

**Comment by thekevinscott** [comment]
More investigation: it looks to be an issue with the SSL certificate.

http://upscaler.ai should redirect correctly.

https://upscaler.ai likely fails.

Looking into how to fix.

**Comment by BooLightning** [comment]
Cleared cookies from the cache and nothing changed.
Also does not work on Chrome or Firefox.
As of now it is still officially ’down’ according to https://downfor.io/upscaler.ai.

P.S. I am on an iPad, which may alter the results

**Comment by thekevinscott** [comment]
Can you try now? I updated the SSL certificate.

**Comment by BooLightning** [comment]
It’s working!

**Comment by thekevinscott** [comment]
Woohoo!
