### ISSUE TITLE
Leaking tensors

### ISSUE THREAD

**Issue by danwexler** [thekevinscott/UpscalerJS#61]
I've found a number of memory leaks in your code where tensors are not properly disposed. My code is now different than this library (this was super helpful!), but I'll try to list the changes here in case someone else has time to make a PR:

src/upscale.ts:296: wrap getProcessedPixels in tf.tidy
src/upscale.ts:308: wrap getProcessedPixels in tf.tidy
src/upscale.ts:238: slicedPixels.dispose
src/upscale.ts: the individual tile tensors need to be disposed, but my changes are a bit more than a single line
src/warmup.ts:46: store tf.zeros in a tmp var and dispose at end (otherwise leaked)

Best way to check this is to run an upscale and print out the TF memoryStats after each one and verify that the memory does not increase. There is a fixed amount of memory required to hold the compiled shaders, but I needed to make the above changes in order to get my code working in tfjs-node-gpu, which is more stringent about memory use.

**Comment by thekevinscott** [comment]
This is great stuff, thanks for documenting these trouble spots @danwexler.

If anyone from the community wants to jump on this, you are more than welcome. Otherwise I'll take it on.

**Comment by thekevinscott** [comment]
This should not have been closed, I’ve removed stalebot.

**Comment by thekevinscott** [comment]
This is now fixed in PR #213
