### ISSUE TITLE
Large images crash V8 JavaScript engine

### ISSUE THREAD

**Issue by hughpearse** [thekevinscott/UpscalerJS#752]
**Describe the bug**
large images cause V8 JavaScript engine to crash

**To Reproduce**
upload large image here 
https://upscalerjs.com/demo

**Expected behavior**
large images should take longer to load (minutes or hours)

**Screenshots**
![mars-attacks-martians-social](https://user-images.githubusercontent.com/681555/210184471-4f40caa6-3bb6-40f8-a8ae-f7f9001521b7.jpg)

![Screenshot_2023-01-01-20-57-55-144_com android chrome](https://user-images.githubusercontent.com/681555/210184452-86bf9692-c8db-46a6-aa4b-4e83f1d2d87a.jpg)
![Screenshot_2023-01-01-20-58-44-140_com android chrome](https://user-images.githubusercontent.com/681555/210184455-d2685699-381a-4e23-9da8-0b2edcb5807b.jpg)
![Screenshot_2023-01-01-20-59-32-280_com android chrome](https://user-images.githubusercontent.com/681555/210184456-bfedcede-88f3-44a1-8996-83067c8cd25c.jpg)
![Screenshot_2023-01-01-20-59-38-004_com android chrome](https://user-images.githubusercontent.com/681555/210184457-c713644a-77d2-471c-85f3-d9355d0ce7ec.jpg)

**Additional context**
a warning is displayed before executing:
Your image is 1400 by 700 pixels. Large images can take a long time to upscale in the browser.

We recommend first downscaling your image to to 600 by 300 pixels before upscaling to demonstrate UpscalerJS.

**Comment by thekevinscott** [comment]
This is sort of a limitation of the hardware you're running on and / or the size of the image you're trying to upscale. Upscaling in the browser is best for smaller images, which is what the warning (`We recommend first downscaling your image to to 600 by 300 pixels before upscaling to demonstrate UpscalerJS.`) is trying to communicate.

As an alternative, you can try upscaling the image in Node.js. Here's an example:

https://codesandbox.io/s/jolly-glitter-y1gxmj?file=/src/index.js:0-1628

This is still slow as codesandbox doesn't offer the beefiest server, but if you run it locally it should be a bit faster. You can also play with the `patchSize` settings, larger settings will run faster but too large will exhaust your computer. (And if you have access to the GPU, definitely use that as that will be _significantly_ faster.)

As far as upscaling images directly in the browser, I'll take another look at this in particular, though I'll caution there's a limit beyond which it's just not feasible to do so. I'm not sure exactly what that limit is - it's a tradeoff between hardware and image size.

Two follow up questions:

- If you try it with the downscaled version (e.g., the image at 600x300 pixels), does that work?
- What's the device hardware you're running on?

**Comment by thekevinscott** [comment]
Also, the browser demo uses a smaller model (`esrgan-slim`), in the Node example I shared I switched it to `esrgan-thick` which is beefier but also slower and not great for the browser. There's also an 8x scale version in the `esrgan-thick` model you could try in Node.

**Comment by thekevinscott** [comment]
I've just pushed an update to the demo page that should improve performance on the rendering side. See if that has any noticeable effect on your device.

**Comment by thekevinscott** [comment]
Closing this; if you're still seeing this issue, feel free to reopen.
