### ISSUE TITLE
Cancel active operation?

### ISSUE THREAD

**Issue by danwexler** [thekevinscott/UpscalerJS#9]
Upscale on larger images can take awhile. Might be nice to be able to cancel active upscales. Perhaps via the return value of the progress() callback?

**Comment by danwexler** [comment]
I've implemented this in my tree for testing using the following patch (works in both Browser Worker and node):

`diff --git a/node_modules/upscaler/dist/upscale.js b/node_modules/upscaler/dist/upscale.js
index 77d57fc..a9c0733 100644
--- a/node_modules/upscaler/dist/upscale.js
+++ b/node_modules/upscaler/dist/upscale.js
@@ -138,7 +138,7 @@ exports.predict = (model, pixels, modelDefinition, { progress, patchSize, paddin
                 yield tf.nextFrame();
                 if (progress) {
                     const index = row * columns + col + 1;
-                    progress(index / total);
+                    if (progress(index / total)) throw new Error('Upscale canceled')
                 }
                 const slicedPrediction = prediction.slice([0, sliceOrigin[0] * scale, sliceOrigin[1] * scale], [-1, sliceSize[0] * scale, sliceSize[1] * scale]);
                 yield tf.nextFrame();
`

**Comment by thekevinscott** [comment]
Being able to cancel an upscale operation is a fantastic idea.

I'm not sure I love the idea of doing it via the `progress` callback, though. To me, leveraging something like an [abortable promise](https://www.npmjs.com/package/promise-abortable) feels more intuitive, so you could do something like:

```
const pendingOperation = upscaler.upscale();

pendingOperation.abort();
```

Alternatively, `fetch` has a similar API, and uses [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to accomplish the same. A bit more verbose of an approach.

I also think having a top-level `abortAll` (or `cancelAll`?) would be useful, so you don't need to manually keep track of all ongoing operations.

Thoughts?

**Comment by thekevinscott** [comment]
This has been implemented in:

 https://github.com/thekevinscott/UpscalerJS/pull/235

https://upscalerjs.com/#/?id=abort
