### ISSUE TITLE
Issues with patch sizes and MAXIM models

### ISSUE THREAD

**Issue by thekevinscott** [thekevinscott/UpscalerJS#913]
I'm working on integrating new MAXIM models in #842, but running into an issue that I'm not sure is solvable. Pinging @danwexler because I think you're working on the same thing and am curious if you have any feedback.

These MAXIM models have fixed input sizes (more on why below), which requires images be split into patches. For some models, this works fine. For others, it does not.

### The models that seem stable when splitting into patches

**Deblurring**
![fixture](https://user-images.githubusercontent.com/151596/222920759-01630653-8433-4ce9-90ee-2c8c90f0b541.png)

![result](https://user-images.githubusercontent.com/151596/222920757-8ea9eb6e-fa67-452f-a518-f420558dfe3f.png)

**Dehazing**
![fixture](https://user-images.githubusercontent.com/151596/222920765-2fc45e1d-4869-4132-80f1-5fa7ce29e421.png)

![result](https://user-images.githubusercontent.com/151596/222920771-2f261c83-b398-48e4-8423-0a62f34826c7.png)

**Deraining**
![fixture](https://user-images.githubusercontent.com/151596/222920776-30fb09c5-b11b-4fe6-ab64-b28cd4ec0816.png)

![result](https://user-images.githubusercontent.com/151596/222920781-19d2981e-79ef-4ee4-88c5-8880e281ccb4.png)

**Dehazing Indoor**
![fixture](https://user-images.githubusercontent.com/151596/222920841-e515bc09-d48d-459b-9670-8e775f0f2b98.png)

![result](https://user-images.githubusercontent.com/151596/222920846-d078778a-6f7a-4b30-ba01-eb3b08bdb130.png)

### The models that exhibit artifacting when splitting into patches

**Dehazing Outdoor**
![fixture](https://user-images.githubusercontent.com/151596/222920851-59c48fe1-ebe3-4630-a2d7-568391bceffa.png)

![result](https://user-images.githubusercontent.com/151596/222920857-7c2f32c8-6cb6-440a-8a4c-2b5176c99dbb.png)

**Low Light Enhancement**

![fixture](https://user-images.githubusercontent.com/151596/222920881-0479f4eb-3181-4277-9484-63d0be3161e4.png)

![result](https://user-images.githubusercontent.com/151596/222920888-65a7840d-3acc-40a9-8c17-c57ce3e1080c.png)

**Retouching**

![fixture](https://user-images.githubusercontent.com/151596/222920895-a904e575-611b-4a00-9e8b-b03cf8366560.png)

![result](https://user-images.githubusercontent.com/151596/222920898-17f93a93-9055-4bdf-9993-4e318c6506b6.png)

I'm converting both the original [JAX implementation](https://github.com/sayakpaul/maxim-tf) along with the [TF versions](https://github.com/google-research/maxim). (For some reason, the converted TF versions run much faster but perform worse than their JAX counterparts; I don't know why.)

## Why the models require fixed input sizes

Both the JAX and TF versions of the models require fixed input sizes when converting to Tensorflow.js. I believe the reason is because both rely on [`einops` functions, which do not support dynamic shapes](https://github.com/arogozhnikov/einops/issues/187).

In the case of the TF version, there's open PRs ([here](https://github.com/sayakpaul/maxim-tf/pull/24) and [here](https://github.com/sayakpaul/maxim-tf/pull/20)) to support arbitrary image sizes, but they're not merged yet.

On the JAX side, similar work would have to be done to deprecate the usage of `einops`.

## Open questions

Is there any way to adjust these models to work across images subdivided into patches? I don't think there is.

So the models could be rewritten to support arbitrary image sizes, but that I think will preclude them from being usable in the browser. Which is maybe the best that can be done for now.

**Comment by thekevinscott** [comment]
This will be resolved in #842.

I was able to convert the Jax model to accept dynamic input shapes.

If and when the [TF port's PR for supporting dynamic shapes is merged](https://github.com/sayakpaul/maxim-tf/pull/24), I'll try and work on porting those to Tensorflow.js as well.

**Comment by danwexler** [comment]
I'm still waiting for full arbitrary resolution support in maxim, which
seems to be progressing recently.
