### ISSUE TITLE
React example is broken

### ISSUE THREAD

**Issue by AlejandroGutierrezB** [thekevinscott/UpscalerJS#914]
**Describe the bug**
The link to the react example in [stackblitz](https://stackblitz.com/github/thekevinscott/upscalerjs/tree/main/examples/react-demo?file=src/App.js&title=UpscalerJS:%20React%20Integration) is broken just fyi

**Comment by thekevinscott** [comment]
Thanks for the report! Should be fixed now (correct link is https://stackblitz.com/github/thekevinscott/upscalerjs/tree/main/examples/react?file=src/App.js&title=UpscalerJS:%20React%20Integration)
